apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    labels:
      ingress-ready: "true"
      kubernetes.io/os: "linux"
  - role: worker
    labels:
      kubernetes.io/os: "linux"
  - role: worker
    labels:
      kubernetes.io/os: "linux"


# kind create cluster --config kind-multi-worker.yaml 이렇게 사용함. 마스터 한개, 워커 2개.