#!/usr/bin/env bash

# kubeconfig 디렉터리가 없으면 생성
if [ ! -d "${HOME}/.kube" ]; then
  mkdir -p "${HOME}/.kube"
fi

exec podman run --rm \
  -v "${HOME}/.kube:/root/.kube:Z" \
  -v "$(pwd):/workdir:Z" \
  bitnami/kubectl:latest \
  kubectl "$@"
