apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: ealen/echo-server:v1.26.0 # 명시적으로 version 을 달아주는 Immutable Infrastructure 에 맞음.
        ports:
        - containerPort: 80  # 단지 “이 컨테이너는 이 포트를 쓴다” 라는 선언적 메타데이터일 뿐이므로, 외부 접근용 포트 매핑은 Service (ClusterIP/NodePort/LoadBalancer) 혹은 hostPort를 사용해야함.
        resources:
          requests:
            cpu:    100m   # 최소 0.1 CPU 보장
            memory: 128Mi  # 최소 128MiB 보장
          limits:
            cpu:    200m   # 최대 0.2 CPU 제한
            memory: 256Mi  # 최대 256MiB 제한
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
#type: ClusterIP # (기본값이므로 생략 가능), 하지만 여기서는 ClusterIP 를 사용하면 외부에서 접근이 불가능함으로 NodePort 를 써야 함.
  type: NodePort 
  selector:
    app: echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080   # 호스트(노드)에서 열릴 포트
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: echo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              number: 80
